import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import LayoutBackground from "@/components/common/LayoutBackground.server";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] })
const oswald = Oswald({ subsets: ["latin"], display: "swap", variable: "--font-poppins" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative p-2 h-dvh max-h-fit  ${inter.className} ${oswald.variable}`}>
        <LayoutBackground />
        {children}
      </body>
    </html>
  );
}
